import Head from "next/head"
import React from "react"
import Header from "../header/Header"

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-slate-50 min-h-screen dark:bg-black dark:text-white">
                <Header />
                {children}
            </main>
        </>
    )
}

export default Layout
